"""Generate a .env.template file from one or more parsed env dicts.

The template strips values, leaving only keys (and optional comments),
so it can be committed to version control as a reference.
"""
from __future__ import annotations

import os
from pathlib import Path
from typing import Iterable


def _sorted_keys(envs: Iterable[dict[str, str]]) -> list[str]:
    """Return a sorted, deduplicated union of all keys across envs."""
    keys: set[str] = set()
    for env in envs:
        keys.update(env.keys())
    return sorted(keys)


def generate_template(
    envs: Iterable[dict[str, str]],
    *,
    include_example_values: bool = False,
    comment_prefix: str = "# ",
) -> str:
    """Return the contents of a .env.template as a string.

    Args:
        envs: One or more parsed env dicts (from parse_env_file).
        include_example_values: If True, keep the value from the *first*
            env that defines the key; otherwise emit an empty value.
        comment_prefix: Prefix for the header comment block.
    """
    env_list = list(envs)
    keys = _sorted_keys(env_list)

    lines: list[str] = [
        f"{comment_prefix}Generated by envdiff templater — do not store real secrets here.",
        "",
    ]

    for key in keys:
        if include_example_values:
            value = next((e[key] for e in env_list if key in e), "")
        else:
            value = ""
        lines.append(f"{key}={value}")

    lines.append("")  # trailing newline
    return os.linesep.join(lines)


def save_template(
    envs: Iterable[dict[str, str]],
    output_path: str | Path,
    *,
    include_example_values: bool = False,
) -> Path:
    """Write a template file to *output_path* and return the resolved path."""
    path = Path(output_path)
    content = generate_template(envs, include_example_values=include_example_values)
    path.write_text(content, encoding="utf-8")
    return path
